// const state=require("../models/state.js");
// const Place=require("../models/place.js");
// const { v4: uuidv4 } = require('uuid');

const placeData = [

    {
      title: "Tirupati Balaji Temple",
      description: "One of the most visited and revered Hindu pilgrimage sites dedicated to Lord Venkateswara.",
      city: "Tirupati",
      location: "Tirumala Hills, Tirupati",
      bestTime: "September to March",
      timings: "2:30 AM - 1:30 AM",
      entryFee: "Free (Special Darshan tickets available)",
      image : "https://plus.unsplash.com/premium_photo-1678597956152-4d92c3f4fc8e?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGlydXBhdGklMjBiYWxhaml8ZW58MHx8MHx8fDA%3D",
     category : "religious",
      state : "Andhra Pradesh",
      stateId : 1,

    },
    {
      title: "Araku Valley",
      description: "A scenic hill_station known for coffee plantations, waterfalls, and tribal culture.",
      city: "Visakhapatnam",
      location: "Araku Valley",
      bestTime: "October to March",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1609854534028-b512f5246abc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmlzYWtoYXBhdG5hbXxlbnwwfHwwfHx8MA%3D%3D",
      category : "nature",
      state : "Andhra Pradesh",
      stateId : 1,
    },
    {
      title: "Borra Caves",
      description: "Ancient limestone caves famous for natural rock formations and stalactites.",
      city: "Araku",
      location: "Ananthagiri Hills",
      bestTime: "October to March",
      timings: "10:00 AM - 5:00 PM",
      entryFee: "₹80",
      image : "https://plus.unsplash.com/premium_photo-1702598911851-307ed72ebce8?q=80&w=1176&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "adventure",
      state : "Andhra Pradesh",
      stateId : 1,
    },
    {
      title: "RK Beach",
      description: "Popular beach destination along the Bay of Bengal.",
      city: "Visakhapatnam",
      location: "Beach Road",
      bestTime: "October to February",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1560179406-1c6c60e0dc76?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "Beach",
      state : "Andhra Pradesh",
      stateId : 1,
    },
    {
      title: "Belum Caves",
      description: "The second-largest cave system in India.",
      city: "Kurnool",
      location: "Belum Village",
      bestTime: "October to February",
      timings: "10:00 AM - 5:00 PM",
      entryFee: "₹65",
      image : "https://images.unsplash.com/photo-1510256506868-484d0db06ee2?q=80&w=1112&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "adventure",
      state : "Andhra Pradesh",
      stateId : 1,

    },
    {
      title: "Tawang Monastery",
      description: "India's largest monastery and an important Buddhist center.",
      city: "Tawang",
      location: "Tawang District",
      bestTime: "March to October",
      timings: "7:00 AM - 7:00 PM",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1628070018796-a9f4e2dd482a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "religious",
      state : "Arunachal Pradesh",
      stateId : 2,
      
    },
    {
      title: "Sela Pass",
      description: "High-altitude mountain pass surrounded by snow-covered peaks.",
      city: "Tawang",
      location: "Sela Pass",
      bestTime: "April to October",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1626761627604-f27d98885f4b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "adventure",
      state : "Arunachal Pradesh",
      stateId : 2,
    },
    {
      title: "Ziro Valley",
      description: "Known for lush landscapes and Apatani tribal culture.",
      city: "Ziro",
      location: "Lower Subansiri District",
      bestTime: "March to October",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://travelogyindia.b-cdn.net/storage/app/upload/ziro-valley11.jpg",
      category : "hill_station",
      state : "Arunachal Pradesh",
      stateId : 2,
    },
    {
      title: "Namdapha National Park",
      description: "One of India's largest protected biodiversity areas.",
      city: "Miao",
      location: "Changlang District",
      bestTime: "October to April",
      timings: "8:00 AM - 5:00 PM",
      entryFee: "₹50",
      image : "https://tse1.mm.bing.net/th/id/OIP.6H-El356tihFT99YJE4XqwHaEK?pid=Api&P=0&h=180",
      category : "wildlife",
      state : "Arunachal Pradesh",
      stateId : 2,
    },
    {
      title: "Bomdila",
      description: "Hill town famous for monasteries and Himalayan views.",
      city: "Bomdila",
      location: "West Kameng District",
      bestTime: "March to October",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://tse4.mm.bing.net/th/id/OIP.L6WqkWURgWmeb1bo65i6MQHaFq?pid=Api&P=0&h=180",
      category : "hill_station",
      state : "Arunachal Pradesh",
      stateId : 2,

    },
    {
      title: "Kaziranga National Park",
      description: "UNESCO World Heritage Site famous for the one-horned rhinoceros.",
      city: "Golaghat",
      location: "Kaziranga",
      bestTime: "November to April",
      timings: "7:30 AM - 4:00 PM",
      entryFee: "₹100",
      image : "https://images.unsplash.com/photo-1675296098616-53e3d4a1dd57?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "wildlife",
      state : "Assam",
      stateId : 3,
    },
    {
      title: "Kamakhya Temple",
      description: "One of the most important Shakti Peethas in India.",
      city: "Guwahati",
      location: "Nilachal Hill",
      bestTime: "October to March",
      timings: "5:30 AM - 10:00 PM",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1594803205835-d121cb46e518?q=80&w=1153&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "religious",
      state : "Assam",
      stateId : 3,

    },
    {
      title: "Majuli Island",
      description: "World's largest river island and cultural center of Assam.",
      city: "Majuli",
      location: "Brahmaputra River",
      bestTime: "October to March",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image : "https://tse4.mm.bing.net/th/id/OIP.7O2wMtrDTat5n778itge-AHaFS?pid=Api&P=0&h=180",
      category : "nature",
      state : "Assam",
      stateId : 3,

    },
    {
      title: "Manas National Park",
      description: "UNESCO World Heritage Site rich in biodiversity.",
      city: "Baksa",
      location: "Manas",
      bestTime: "November to April",
      timings: "9:00 AM - 5:00 PM",
      entryFee: "₹100",
      image : "https://d27k8xmh3cuzik.cloudfront.net/wp-content/uploads/2018/05/MNP_700x367.jpg",
      category : "wildlife",
      state : "Assam",
      stateId : 3,

    },
    {
      title: "Umananda Temple",
      description: "Ancient Shiva temple situated on Peacock Island.",
      city: "Guwahati",
      location: "Brahmaputra River",
      bestTime: "October to March",
      timings: "5:30 AM - 6:00 PM",
      entryFee: "Free",
      image :"https://bestofnortheast.com/wp-content/uploads/2025/06/Umananda-Temple-on-Peacock-Island-at-Sunset-1024x512.webp" ,
      category : "religious",
      state : "Assam",
      stateId : 3,

    },
    {
      title: "Mahabodhi Temple",
      description: "UNESCO World Heritage Site where Gautama Buddha attained enlightenment.",
      city: "Bodh Gaya",
      location: "Bodh Gaya",
      bestTime: "October to March",
      timings: "5:00 AM - 9:00 PM",
      entryFee: "Free",
      image : "https://images.unsplash.com/photo-1679806893392-29f024308936?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFoYWJvZGhpJTIwdGVtcGxlfGVufDB8fDB8fHww",
      category : "religious",
      state : "Bihar",
      stateId : 4,

    },
    {
      title: "Nalanda University Ruins",
      description: "Ancient center of learning and UNESCO World Heritage Site.",
      city: "Nalanda",
      location: "Nalanda",
      bestTime: "October to March",
      timings: "9:00 AM - 5:00 PM",
      entryFee: "₹40",
      image : "https://images.unsplash.com/photo-1736235300171-eb8aa382b594?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "heritage",
      state : "Bihar",
      stateId : 4,

    },
    {
      title: "Vishwa Shanti Stupa",
      description: "Beautiful peace pagoda overlooking Rajgir.",
      city: "Rajgir",
      location: "Ratnagiri Hill",
      bestTime: "October to March",
      timings: "8:00 AM - 5:00 PM",
      entryFee: "Free",
      image :"https://tse1.mm.bing.net/th/id/OIP.AN9b7c6yPD94iT5pUmTlxAHaFj?pid=Api&P=0&h=180",
      category : "religious",
      state : "Bihar",
      stateId : 4,

    },
    {
      title: "Golghar",
      description: "Historic granary and popular viewpoint.",
      city: "Patna",
      location: "Patna",
      bestTime: "October to February",
      timings: "10:00 AM - 5:00 PM",
      entryFee: "₹20",
      image : "https://upload.wikimedia.org/wikipedia/commons/9/91/Golghar_%E0%A5%AA.jpg",
      category : "heritage",
      state : "Bihar",
      stateId : 4,

    },
    {
      title: "Vikramshila Ruins",
      description: "Ancient Buddhist university site.",
      city: "Bhagalpur",
      location: "Antichak",
      bestTime: "October to March",
      timings: "9:00 AM - 5:00 PM",
      entryFee: "₹25",
      image : "https://tse1.mm.bing.net/th/id/OIP.guskjpij0aQ0nvB8LJUOwgHaEc?pid=Api&P=0&h=180",
      category : "heritage",
      state : "Bihar",
      stateId : 4,

    },
    {
      title: "Chitrakote Falls",
      description: "India's widest waterfall, often called the Niagara of India.",
      city: "Jagdalpur",
      location: "Bastar District",
      bestTime: "July to October",
      timings: "Open 24 Hours",
      entryFee: "Free",
      image: "https://plus.unsplash.com/premium_photo-1667401373119-f9af8c7ccf8e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "nature",
      state : "Chhattisgarh",
      stateId : 5,

    },
    {
      title: "Tirathgarh Falls",
      description: "Magnificent multi-tiered waterfall in Kanger Valley.",
      city: "Jagdalpur",
      location: "Kanger Valley National Park",
      bestTime: "July to February",
      timings: "8:00 AM - 5:00 PM",
      entryFee: "₹25",
      image: "https://plus.unsplash.com/premium_photo-1664361480975-4c63828f5d88?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "nature",
      state : "Chhattisgarh",
      stateId : 5,

    },
    {
      title: "Kanger Valley National Park",
      description: "Known for caves, waterfalls, and rich biodiversity.",
      city: "Jagdalpur",
      location: "Bastar Region",
      bestTime: "October to June",
      timings: "7:00 AM - 5:00 PM",
      entryFee: "₹50",
      image: "https://i.ytimg.com/vi/f-Ej5kjcZEo/maxresdefault.jpg",
      category : "nature",
      state : "Chhattisgarh",
      stateId : 5,

    },
    {
      title: "Bhoramdeo Temple",
      description: "Ancient temple complex often called the Khajuraho of Chhattisgarh.",
      city: "Kawardha",
      location: "Kabirdham District",
      bestTime: "October to March",
      timings: "6:00 AM - 7:00 PM",
      entryFee: "Free",
      image : "https://plus.unsplash.com/premium_photo-1694475136007-14c4dbf484f5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "religious",
      state : "Chhattisgarh",
      stateId : 5,

    },
    {
      title: "Sirpur",
      description: "Historic archaeological site with Buddhist and Hindu monuments.",
      city: "Mahasamund",
      location: "Sirpur",
      bestTime: "October to March",
      timings: "8:00 AM - 5:00 PM",
      entryFee: "₹25",
      image : "https://tse2.mm.bing.net/th/id/OIP.7tZx5QUS5GmqwcYK4gRHEAHaFj?pid=Api&P=0&h=180",
      category : "heritage",
      state : "Chhattisgarh",
      stateId : 5

    },
{
    title: "Baga Beach",
    description: "One of Goa's most famous beaches known for water sports, nightlife, and vibrant beach shacks.",
    city: "Baga",
    location: "North Goa",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://images.unsplash.com/photo-1757702244726-00198554c4a0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "Beach",
    state: "Goa",
    stateId: 6,
},
{
    title: "Basilica of Bom Jesus",
    description: "UNESCO World Heritage Site housing the mortal remains of St. Francis Xavier.",
    city: "Old Goa",
    location: "Old Goa",
    bestTime: "November to February",
    timings: "9:00 AM - 6:30 PM",
    entryFee: "Free",
    image : "https://plus.unsplash.com/premium_photo-1678197482537-85638a5414c0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Goa",
    stateId: 6,
},
{
    title: "Dudhsagar Falls",
    description: "A spectacular four-tiered waterfall located on the Mandovi River.",
    city: "Sanguem",
    location: "Bhagwan Mahavir wildlife Sanctuary",
    bestTime: "July to October",
    timings: "6:00 AM - 5:00 PM",
    entryFee: "₹30",
    image : "https://images.unsplash.com/photo-1620766165457-a8025baa82e0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZHVkaHNhZ2FyJTIwZmFsbHN8ZW58MHx8MHx8fDA%3D",
    category:"nature",
    state: "Goa",
    stateId: 6,
},
{
    title: "Fort Aguada",
    description: "A well-preserved Portuguese fort overlooking the Arabian Sea.",
    city: "Candolim",
    location: "North Goa",
    bestTime: "November to February",
    timings: "8:30 AM - 5:30 PM",
    entryFee: "Free",
    image : "https://images.unsplash.com/photo-1727786473209-5a3a7747e877?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Goa",
    stateId: 6,
},
{
    title: "Anjuna Beach",
    description: "Popular beach known for flea markets, nightlife, and scenic coastline.",
    city: "Anjuna",
    location: "North Goa",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://plus.unsplash.com/premium_photo-1675860544617-c0f2afa2f94e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "Beach",
    state: "Goa",
    stateId: 6,
},

{
    title: "Statue of Unity",
    description: "World's tallest statue dedicated to Sardar Vallabhbhai Patel.",
    city: "Kevadia",
    location: "Narmada District",
    bestTime: "October to March",
    timings: "8:00 AM - 6:00 PM",
    entryFee: "₹150",
    image: "https://images.unsplash.com/photo-1631983097767-099c77bf880d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3RhdHVlJTIwb2YlMjB1bml0eXxlbnwwfHwwfHx8MA%3D%3D",
      category : "heritage",
    state: "Gujarat",
    stateId: 7,
},
{
    title: "Somnath Temple",
    description: "One of the twelve Jyotirlinga shrines and a major Hindu pilgrimage site.",
    city: "Somnath",
    location: "Prabhas Patan",
    bestTime: "October to March",
    timings: "6:00 AM - 10:00 PM",
    entryFee: "Free",
    image: "https://images.unsplash.com/photo-1735192683809-3fcd83233e19?q=80&w=524&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Gujarat",
    stateId: 7,
},
{
    title: "Gir National Park",
    description: "The only natural habitat of Asiatic Lions in the world.",
    city: "Junagadh",
    location: "Gir Forest",
    bestTime: "December to March",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹150",
    image: "https://images.unsplash.com/photo-1634046808105-ce0ec912691e?q=80&w=1163&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "wildlife",
    state: "Gujarat",
    stateId: 7,
},
{
    title: "Rann of Kutch",
    description: "A vast white salt desert famous for the Rann Utsav festival.",
    city: "Bhuj",
    location: "Kutch District",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "₹100",
    image: "https://images.unsplash.com/photo-1670406312373-6d4d1776e4aa?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmFubiUyMG9mJTIwa3V0Y2h8ZW58MHx8MHx8fDA%3D",
    category : "nature",
    state: "Gujarat",
    stateId: 7,
},
{
    title: "Dwarkadhish Temple",
    description: "Ancient temple dedicated to Lord Krishna and one of the Char Dham sites.",
    city: "Dwarka",
    location: "Devbhoomi Dwarka",
    bestTime: "October to March",
    timings: "6:30 AM - 9:30 PM",
    entryFee: "Free",
    image :"https://plus.unsplash.com/premium_photo-1691031429475-a18a2c89d83c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Gujarat",
    stateId: 7,
},

{
    title: "Kingdom of Dreams",
    description: "India's first live entertainment and leisure destination.",
    city: "Gurugram",
    location: "Sector 29",
    bestTime: "October to March",
    timings: "12:30 PM - 12:00 AM",
    entryFee: "₹799",
    image: "https://images.unsplash.com/photo-1766156555244-572b9757433b?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "adventure",
    state: "Haryana",
    stateId: 8,
},
{
    title: "Kurukshetra",
    description: "Historic city associated with the Mahabharata and Bhagavad Gita.",
    city: "Kurukshetra",
    location: "Kurukshetra District",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image: "https://images.unsplash.com/photo-1727253112274-ca80addee55c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Haryana",
    stateId: 8,
},
{
    title: "Sultanpur National Park",
    description: "Renowned bird sanctuary attracting migratory birds.",
    city: "Gurugram",
    location: "Sultanpur",
    bestTime: "November to February",
    timings: "7:00 AM - 4:30 PM",
    entryFee: "₹5",
    image: "https://plus.unsplash.com/premium_photo-1677636665512-d210c919fe74?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Haryana",
    stateId: 8,
},
{
    title: "Pinjore Gardens",
    description: "Historic Mughal-style garden with beautiful fountains and terraces.",
    city: "Pinjore",
    location: "Panchkula",
    bestTime: "October to March",
    timings: "7:00 AM - 10:00 PM",
    entryFee: "₹20",
    image: "https://plus.unsplash.com/premium_photo-1680855302067-6aae0782e43c?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Haryana",
    stateId: 8,
},
{
    title: "Morni Hills",
    description: "The only hill_station in Haryana known for scenic landscapes.",
    city: "Morni",
    location: "Panchkula District",
    bestTime: "September to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://plus.unsplash.com/premium_photo-1745937149191-255cda3090fe?q=80&w=1152&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "hill_station",
    state: "Haryana",
    stateId: 8,
},

{
    title: "Shimla Mall Road",
    description: "Popular tourist destination offering shopping, food, and mountain views.",
    city: "Shimla",
    location: "Mall Road",
    bestTime: "March to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://plus.unsplash.com/premium_photo-1697730487072-c7c29e113007?q=80&w=805&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "adventure",
    state: "Himachal Pradesh",
    stateId: 9,
},
{
    title: "Rohtang Pass",
    description: "High mountain pass known for snow activities and breathtaking scenery.",
    city: "Manali",
    location: "Rohtang",
    bestTime: "May to October",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "Permit Required",
    image : "https://plus.unsplash.com/premium_photo-1661962740957-ccd5130e194e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cm9odGFuZyUyMHBhc3N8ZW58MHx8MHx8fDA%3D",
    category : "adventure",
    state: "Himachal Pradesh",
    stateId: 9,
},
{
    title: "Solang Valley",
    description: "adventure destination famous for paragliding, skiing, and snow sports.",
    city: "Manali",
    location: "Solang Valley",
    bestTime: "December to February",
    timings: "8:00 AM - 6:00 PM",
    entryFee: "Free",
    image : "https://images.unsplash.com/photo-1675515642342-2c55067d51d5?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "adventure",
    state: "Himachal Pradesh",
    stateId: 9,
},
{
    title: "Dharamshala",
    description: "Scenic hill town known for Tibetan culture and monasteries.",
    city: "Dharamshala",
    location: "Kangra District",
    bestTime: "March to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://images.unsplash.com/photo-1657894736632-e18fbccf8e7d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "hill_station",
    state: "Himachal Pradesh",
    stateId: 9,
},
{
    title: "Spiti Valley",
    description: "Cold desert mountain valley offering stunning Himalayan landscapes.",
    city: "Kaza",
    location: "Spiti District",
    bestTime: "May to September",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image : "https://plus.unsplash.com/premium_photo-1661878309257-f4343940ce4d?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "adventure",
    state: "Himachal Pradesh",
    stateId: 9,
},

{
    title: "Baidyanath Temple",
    description: "One of the twelve Jyotirlinga temples dedicated to Lord Shiva.",
    city: "Deoghar",
    location: "Baidyanath Dham",
    bestTime: "October to March",
    timings: "4:00 AM - 9:00 PM",
    entryFee: "Free",
    image:"https://media-cdn.tripadvisor.com/media/photo-s/0d/09/7f/87/bol-bam.jpg",
    category : "religious",
    state: "Jharkhand",
    stateId: 10,
},
{
    title: "Hundru Falls",
    description: "One of the highest waterfalls in Jharkhand on the Subarnarekha River.",
    city: "Ranchi",
    location: "Hundru",
    bestTime: "July to December",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹10",
    image: "https://plus.unsplash.com/premium_photo-1745854438760-d1edc2872fa9?q=80&w=685&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Jharkhand",
    stateId: 10,
},
{
    title: "Dassam Falls",
    description: "Beautiful waterfall known for its scenic surroundings.",
    city: "Ranchi",
    location: "Taimara",
    bestTime: "July to December",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹10",
    image: "https://images.unsplash.com/photo-1739261889643-e84775b7ab3b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Jharkhand",
    stateId: 10,
},
{
    title: "Netarhat",
    description: "hill_station known as the Queen of Chotanagpur with picturesque sunsets.",
    city: "Netarhat",
    location: "Latehar District",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://tse1.mm.bing.net/th/id/OIP.3oCNrt0UTZq8NPH-JTvCmAHaDt?pid=Api&P=0&h=180",
    category : "hill_station",
    state: "Jharkhand",
    stateId: 10,
},
{
    title: "Patratu Valley",
    description: "Scenic valley featuring winding roads and beautiful reservoir views.",
    city: "Patratu",
    location: "Ramgarh District",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image: "https://tse4.mm.bing.net/th/id/OIP.SOy_v9W9RmbIHP4tOedaUwHaEK?pid=Api&P=0&h=180",
      category : "nature",
    state: "Jharkhand",
    stateId: 10,
},
 {
    title: "Mysore Palace",
    description: "A magnificent royal palace showcasing Indo-Saracenic architecture and rich heritage.",
    city: "Mysuru",
    location: "Mysore Palace Road",
    bestTime: "October to February",
    timings: "10:00 AM - 5:30 PM",
    entryFee: "₹100",
    image:"https://images.unsplash.com/photo-1590766940554-634a7ed41450?q=80&w=999&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Karnataka",
    stateId: 11,
},
{
    title: "Hampi",
    description: "UNESCO World Heritage Site featuring the ruins of the Vijayanagara Empire.",
    city: "Hampi",
    location: "Vijayanagara District",
    bestTime: "October to February",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹40",
    image: "https://tse2.mm.bing.net/th/id/OIP.cgnJ8I5Bo0rldWAuqe2hnAHaE8?pid=Api&P=0&h=180",
      category : "heritage",
    state: "Karnataka",
    stateId: 11,
},
{
    title: "Coorg",
    description: "Scenic hill_station famous for coffee plantations, waterfalls, and greenery.",
    city: "Madikeri",
    location: "Kodagu District",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://mandakashayam.com/wp-content/uploads/2025/03/Best-places-to-visit-in-Coorg.jpg",
    category : "hill_station",
    state: "Karnataka",
    stateId: 11,
},
{
    title: "Jog Falls",
    description: "One of India's highest waterfalls created by the Sharavathi River.",
    city: "Sagara",
    location: "Shimoga District",
    bestTime: "July to December",
    timings: "8:00 AM - 6:00 PM",
    entryFee: "₹20",
    image: "https://images.unsplash.com/photo-1553679813-b437b57c08f1?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Karnataka",
    stateId: 11,
},
{
    title: "Bangalore Palace",
    description: "Historic palace inspired by England's Windsor Castle.",
    city: "Bengaluru",
    location: "Vasanth Nagar",
    bestTime: "Throughout the Year",
    timings: "10:00 AM - 5:30 PM",
    entryFee: "₹240",
    image: "https://plus.unsplash.com/premium_photo-1697729447666-c39f50d595ea?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Karnataka",
    stateId: 11,
},

{
    title: "Munnar",
    description: "Beautiful hill_station known for tea gardens, misty hills, and cool climate.",
    city: "Munnar",
    location: "Idukki District",
    bestTime: "September to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1637066742971-726bee8d9f56?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bXVubmFyfGVufDB8fDB8fHww",
    category : "hill_station",
    state: "Kerala",
    stateId: 12,
},
{
    title: "Alleppey Backwaters",
    description: "Famous network of lagoons and canals offering houseboat cruises.",
    city: "Alappuzha",
    location: "Alleppey",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Houseboat Charges Apply",
    image:"https://images.unsplash.com/photo-1677475455506-1e429162f44f?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Kerala",
    stateId: 12,
},
{
    title: "Thekkady",
    description: "wildlife destination known for Periyar Tiger Reserve and boating.",
    city: "Thekkady",
    location: "Periyar National Park",
    bestTime: "October to February",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹45",
    image:"https://plus.unsplash.com/premium_photo-1694475205503-d6c6a71f03bc?q=80&w=901&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "wildlife",
    state: "Kerala",
    stateId: 12,
},
{
    title: "Kovalam Beach",
    description: "Popular beach destination known for crescent-shaped shores and lighthouse.",
    city: "Kovalam",
    location: "Thiruvananthapuram",
    bestTime: "September to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://tse3.mm.bing.net/th/id/OIP.dNEM_dtdwqiKaU6ghu_3CQHaE9?pid=Api&P=0&h=180",
    category : "Beach",
    state: "Kerala",
    stateId: 12,
},
{
    title: "Athirappilly Falls",
    description: "Kerala's largest waterfall often called the Niagara of India.",
    city: "Athirappilly",
    location: "Thrissur District",
    bestTime: "June to January",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹30",
    image:"https://images.unsplash.com/photo-1669111586121-1c17f6b228d8?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Kerala",
    stateId: 12,
},

{
    title: "Khajuraho Temples",
    description: "UNESCO World Heritage Site famous for exquisite temple architecture and sculptures.",
    city: "Khajuraho",
    location: "Chhatarpur District",
    bestTime: "October to March",
    timings: "8:00 AM - 6:00 PM",
    entryFee: "₹40",
    image:"https://images.unsplash.com/photo-1671375159250-8f81a29e54e7?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Madhya Pradesh",
    stateId: 13,
},
{
    title: "Sanchi Stupa",
    description: "Ancient Buddhist monument and UNESCO World Heritage Site.",
    city: "Sanchi",
    location: "Raisen District",
    bestTime: "October to March",
    timings: "8:30 AM - 5:30 PM",
    entryFee: "₹40",
    image:"https://images.unsplash.com/photo-1667910664822-6232862d4a80?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Madhya Pradesh",
    stateId: 13,
},
{
    title: "Bandhavgarh National Park",
    description: "One of India's best tiger reserves known for wildlife safaris.",
    city: "Umaria",
    location: "Bandhavgarh",
    bestTime: "October to June",
    timings: "6:00 AM - 11:00 AM",
    entryFee: "Safari Charges Apply",
    image:"https://plus.unsplash.com/premium_photo-1675847898176-824143229880?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "wildlife",
    state: "Madhya Pradesh",
    stateId: 13,
},
{
    title: "Bhimbetka Rock Shelters",
    description: "Prehistoric cave shelters featuring ancient rock paintings.",
    city: "Raisen",
    location: "Bhimbetka",
    bestTime: "October to March",
    timings: "7:00 AM - 6:00 PM",
    entryFee: "₹25",
    image:"https://images.unsplash.com/photo-1675769053353-9db1b9e6efa5?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8QmhpbWJldGthJTIwUm9jayUyMFNoZWx0ZXJzfGVufDB8fDB8fHww",
    category : "heritage",
    state: "Madhya Pradesh",
    stateId: 13,
},
{
    title: "Pachmarhi",
    description: "The only hill_station in Madhya Pradesh known for caves and waterfalls.",
    city: "Pachmarhi",
    location: "Narmadapuram District",
    bestTime: "October to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1704633396200-79f80c9ad208?q=80&w=673&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "hill_station",
    state: "Madhya Pradesh",
    stateId: 13,
},

{
    title: "Gateway of India",
    description: "Iconic monument overlooking the Arabian Sea and symbol of Mumbai.",
    city: "Mumbai",
    location: "Apollo Bunder",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1598434192043-71111c1b3f41?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"heritage",
    state: "Maharashtra",
    stateId: 14,
},
{
    title: "Ajanta Caves",
    description: "UNESCO World Heritage Site featuring ancient Buddhist cave paintings.",
    city: "Aurangabad",
    location: "Ajanta",
    bestTime: "October to March",
    timings: "9:00 AM - 5:30 PM",
    entryFee: "₹40",
    image:"https://plus.unsplash.com/premium_photo-1697729588019-20a1f5a325d1?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Maharashtra",
    stateId: 14,
},
{
    title: "Ellora Caves",
    description: "Historic cave complex famous for rock-cut temples and monasteries.",
    city: "Aurangabad",
    location: "Ellora",
    bestTime: "October to March",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹40",
    image:"https://tse4.mm.bing.net/th/id/OIP.8MRsKPPwwEIKvQCg_L7qoQHaEK?pid=Api&P=0&h=180",
    category : "heritage",
    state: "Maharashtra",
    stateId: 14,
},
{
    title: "Mahabaleshwar",
    description: "Popular hill_station known for viewpoints, strawberries, and pleasant weather.",
    city: "Mahabaleshwar",
    location: "Satara District",
    bestTime: "October to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1649404812224-ff1c5c72e9a7?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "hill_station",
    state: "Maharashtra",
    stateId: 14,
},
{
    title: "Shirdi Sai Baba Temple",
    description: "One of India's most visited pilgrimage sites dedicated to Sai Baba.",
    city: "Shirdi",
    location: "Ahmednagar District",
    bestTime: "October to March",
    timings: "4:00 AM - 11:00 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1629640890590-7836d69c5237?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Maharashtra",
    stateId: 14,
},

{
    title: "Loktak Lake",
    description: "The largest freshwater lake in Northeast India known for floating islands.",
    city: "Moirang",
    location: "Bishnupur District",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1760637626688-a9fc45b672b3?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Manipur",
    stateId: 15,
},
{
    title: "Keibul Lamjao National Park",
    description: "The world's only floating national park and home of the Sangai deer.",
    city: "Bishnupur",
    location: "Loktak Lake Region",
    bestTime: "November to April",
    timings: "9:00 AM - 5:00 PM",
    entryFee: "₹30",
    image:"https://mytravelframes.com/wp-content/uploads/2023/01/IMG_20221230_151735.jpg",
    category : "wildlife",
    state: "Manipur",
    stateId: 15,
},
{
    title: "Kangla Fort",
    description: "Historic fort complex representing the cultural heritage of Manipur.",
    city: "Imphal",
    location: "Kangla",
    bestTime: "October to March",
    timings: "9:00 AM - 4:30 PM",
    entryFee: "₹20",
    image:"https://plus.unsplash.com/premium_photo-1691031428357-e8a7706206e1?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Manipur",
    stateId: 15,
},
{
    title: "Shree Govindajee Temple",
    description: "Important Vaishnavite temple dedicated to Lord Krishna.",
    city: "Imphal",
    location: "Palace Compound",
    bestTime: "October to March",
    timings: "5:00 AM - 8:30 PM",
    entryFee: "Free",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZbxUwAJ825ktkuEoVL3d-fIUIfPEvaWlsvKjL87XFsw&s=10",
    category : "religious",
    state: "Manipur",
    stateId: 15,
},
{
    title: "INA Memorial Complex",
    description: "Historic site commemorating the Indian National Army's contribution to independence.",
    city: "Moirang",
    location: "Moirang",
    bestTime: "October to March",
    timings: "9:00 AM - 5:00 PM",
    entryFee: "₹10",
    image:"https://upload.wikimedia.org/wikipedia/commons/5/51/INA_Memorial%2C_Moirang%2C_Manipur_%2816%29.jpeg",
      category : "heritage",
    state: "Manipur",
    stateId: 15,
},
   {
    title: "Nohkalikai Falls",
    description: "India's tallest plunge waterfall offering breathtaking views of lush valleys.",
    city: "Cherrapunji",
    location: "East Khasi Hills",
    bestTime: "October to May",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹20",
    image:"https://images.unsplash.com/photo-1637043765564-a071ff91a09f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "nature",
    state: "Meghalaya",
    stateId: 16,
},
{
    title: "Living Root Bridge",
    description: "Unique natural bridge formed by intertwining roots of rubber trees.",
    city: "Cherrapunji",
    location: "Nongriat Village",
    bestTime: "October to May",
    timings: "6:00 AM - 5:00 PM",
    entryFee: "Free",
    image : "https://images.unsplash.com/photo-1625654325562-762dcec9e6f2?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Meghalaya",
    stateId: 16,
},
{
    title: "Umiam Lake",
    description: "Scenic reservoir surrounded by green hills and popular for water sports.",
    city: "Shillong",
    location: "Umiam",
    bestTime: "October to April",
    timings: "9:00 AM - 5:00 PM",
    entryFee: "Free",
    image: "https://images.unsplash.com/photo-1665248919075-246d0ac9a912?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Meghalaya",
    stateId: 16,
},
{
    title: "Shillong Peak",
    description: "Highest point in Meghalaya offering panoramic views of Shillong city.",
    city: "Shillong",
    location: "Shillong Peak",
    bestTime: "September to May",
    timings: "9:00 AM - 3:30 PM",
    entryFee: "₹30",
    image : "https://plus.unsplash.com/premium_photo-1723741285257-378423c8fbef?q=80&w=1309&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Meghalaya",
    stateId: 16,
},
{
    title: "Mawlynnong",
    description: "Known as Asia's cleanest village with picturesque surroundings.",
    city: "Mawlynnong",
    location: "East Khasi Hills",
    bestTime: "October to April",
    timings: "Open 24 Hours",
    entryFee: "₹20",
    image:"https://images.unsplash.com/photo-1587623345880-c8ec53847c25?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TWF3bHlubm9uZ3xlbnwwfHwwfHx8MA%3D%3D",
    category : "nature",
    state: "Meghalaya",
    stateId: 16,
},

{
    title: "Vantawng Falls",
    description: "The highest waterfall in Mizoram surrounded by dense forests.",
    city: "Thenzawl",
    location: "Serchhip District",
    bestTime: "October to April",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹20",
    image:"https://images.unsplash.com/photo-1637043765564-a071ff91a09f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Mizoram",
    stateId: 17,
},
{
    title: "Reiek Peak",
    description: "Popular trekking destination offering spectacular mountain views.",
    city: "Reiek",
    location: "Mamit District",
    bestTime: "October to March",
    timings: "6:00 AM - 5:00 PM",
    entryFee: "₹10",
    image:"https://i0.wp.com/aravindgundumane.com/wp-content/uploads/2022/11/Reiek-peak.jpg?resize=1103%2C735&ssl=1",
    category : "adventure",
    state: "Mizoram",
    stateId: 17,
},
{
    title: "Phawngpui Blue mountain",
    description: "Highest mountain in Mizoram known for rare flora and scenic beauty.",
    city: "Lawngtlai",
    location: "Phawngpui National Park",
    bestTime: "October to April",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹50",
    image:"https://images.unsplash.com/photo-1515266591878-f93e32bc5937?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "mountain",
    state: "Mizoram",
    stateId: 17,
},
{
    title: "Solomon's Temple",
    description: "Magnificent church complex and important religious landmark.",
    city: "Aizawl",
    location: "Kidron Valley",
    bestTime: "Throughout the Year",
    timings: "9:00 AM - 5:00 PM",
    entryFee: "Free",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxwN1sg3-A_id6SoM3pNcTw2I8XygI2DCQGEDichuJ9_4W4nzt44XjfVfk&s=10",
    category : "religious",
    state: "Mizoram",
    stateId: 17,
},
{
    title: "Tamdil Lake",
    description: "Beautiful natural lake surrounded by evergreen forests.",
    city: "Saitual",
    location: "Tamdil",
    bestTime: "October to April",
    timings: "Open 24 Hours",
    entryFee: "₹10",
    image:"https://tse1.mm.bing.net/th/id/OIP.lAaGRJEZCTwKQV928NPEbgHaE3?pid=Api&P=0&h=180",
    category : "nature",
    state: "Mizoram",
    stateId: 17,
},

{
    title: "Dzukou Valley",
    description: "Picturesque valley famous for seasonal flowers and trekking trails.",
    city: "Kohima",
    location: "Nagaland-Manipur Border",
    bestTime: "June to September",
    timings: "Open 24 Hours",
    entryFee: "₹50",
    image:"https://images.unsplash.com/photo-1712055196088-9bc6da4ffbce?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Nagaland",
    stateId: 18,
},
{
    title: "Kohima War Cemetery",
    description: "Memorial dedicated to soldiers who fought during World War II.",
    city: "Kohima",
    location: "Kohima Town",
    bestTime: "October to April",
    timings: "8:00 AM - 4:00 PM",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1680854771656-9708edc39cee?q=80&w=984&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "heritage",
    state: "Nagaland",
    stateId: 18,
},
{
    title: "Khonoma Village",
    description: "India's first green village known for eco-tourism and Angami culture.",
    city: "Khonoma",
    location: "Kohima District",
    bestTime: "October to April",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://upload.wikimedia.org/wikipedia/commons/b/b4/View_of_Khonoma_%282024%29.jpg",
    category : "nature",
    state: "Nagaland",
    stateId: 18,
},
{
    title: "Japfu Peak",
    description: "Second-highest mountain in Nagaland offering trekking adventures.",
    city: "Kohima",
    location: "Japfu Range",
    bestTime: "October to April",
    timings: "6:00 AM - 5:00 PM",
    entryFee: "Free",
    image:"https://mlzskshygvou.i.optimole.com/w:1003/h:1080/q:mauto/ig:avif/https://wanderzoned.com/wp-content/uploads/2025/03/qtbftfjim9tajqex0snq-scaled-e1740864850887.webp",
    category : "mountain",
    state: "Nagaland",
    stateId: 18,
},
{
    title: "Shilloi Lake",
    description: "Scenic natural lake surrounded by hills and local folklore.",
    city: "Phek",
    location: "Shilloi",
    bestTime: "October to April",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/42/c0/4f/prestine-nature.jpg?w=900&h=500&s=1",
    category : "nature",
    state: "Nagaland",
    stateId: 18,
},

{
    title: "Jagannath Temple",
    description: "One of the Char Dham pilgrimage sites dedicated to Lord Jagannath.",
    city: "Puri",
    location: "Grand Road",
    bestTime: "October to February",
    timings: "5:00 AM - 10:00 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1706790574525-d218c4c52b5c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Odisha",
    stateId: 19,
},
{
    title: "Konark Sun Temple",
    description: "UNESCO World Heritage Site renowned for its stunning stone carvings.",
    city: "Konark",
    location: "Puri District",
    bestTime: "October to March",
    timings: "6:00 AM - 8:00 PM",
    entryFee: "₹40",
    image:"https://plus.unsplash.com/premium_photo-1694475136007-14c4dbf484f5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      category : "heritage",
    state: "Odisha",
    stateId: 19,
},
{
    title: "Chilika Lake",
    description: "Asia's largest brackish water lagoon famous for migratory birds.",
    city: "Puri",
    location: "Chilika",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Boat Charges Apply",
    image:"https://plus.unsplash.com/premium_photo-1713375115181-edb9c7e7b379?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "nature",
    state: "Odisha",
    stateId: 19,
},
{
    title: "Lingaraj Temple",
    description: "Ancient Hindu temple showcasing classic Kalinga architecture.",
    city: "Bhubaneswar",
    location: "Old Town",
    bestTime: "October to March",
    timings: "5:00 AM - 9:00 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1598323646582-18d2101c9aad?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Odisha",
    stateId: 19,
},
{
    title: "Udayagiri and Khandagiri Caves",
    description: "Historic rock-cut caves associated with Jain monks and ancient Odisha.",
    city: "Bhubaneswar",
    location: "Khandagiri",
    bestTime: "October to March",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹25",
    image:"https://images.unsplash.com/photo-1715534257641-12c2933a508f?q=80&w=1031&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Odisha",
    stateId: 19,
},

{
    title: "Golden Temple",
    description: "The holiest Sikh shrine known for its golden architecture and spiritual significance.",
    city: "Amritsar",
    location: "Harmandir Sahib",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1697730426305-113c62434f97?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "religious",
    state: "Punjab",
    stateId: 20,
},
{
    title: "Jallianwala Bagh",
    description: "Historic memorial commemorating the victims of the 1919 massacre.",
    city: "Amritsar",
    location: "Near Golden Temple",
    bestTime: "October to March",
    timings: "6:30 AM - 7:30 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1644406733884-f90d90af8bc8?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Punjab",
    stateId: 20,
},
{
    title: "Wagah Border",
    description: "Famous for the daily Beating Retreat ceremony between India and Pakistan.",
    city: "Amritsar",
    location: "Attari-Wagah Border",
    bestTime: "October to March",
    timings: "10:00 AM - 4:00 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1651910031211-42aaa52b87cc?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category : "heritage",
    state: "Punjab",
    stateId: 20,
},
{
    title: "Anandpur Sahib",
    description: "Important Sikh pilgrimage site and birthplace of the Khalsa.",
    city: "Anandpur Sahib",
    location: "Rupnagar District",
    bestTime: "October to March",
    timings: "4:00 AM - 10:00 PM",
    entryFee: "Free",
    image:"https://www.oyorooms.com/travel-guide/wp-content/uploads/2020/01/Generic-19-1.jpg",
    category : "religious",
    state: "Punjab",
    stateId: 20,
},
{
    title: "Sheesh Mahal Patiala",
    description: "Historic palace featuring beautiful mirror work and museum collections.",
    city: "Patiala",
    location: "Old Moti Bagh Palace Complex",
    bestTime: "October to March",
    timings: "10:00 AM - 5:00 PM",
    entryFee: "₹20",
    image:"https://s7ap1.scene7.com/is/image/incredibleindia/sheesh-mahal-patiala-punjab-1-attr-hero?qlt=82&ts=1742180406649",
    category : "heritage",
    state: "Punjab",
    stateId: 20,
},
  {
    title: "Hawa Mahal",
    description:
      "The Hawa Mahal, also known as the Palace of Winds, is a five-story pink sandstone structure built in 1799. It is famous for its unique honeycomb design and numerous small windows.",
    city: "Jaipur",
      location: "Jaipur, Rajasthan",
      bestTime: "October to March",
      timings: "9:00 AM - 5:00 PM",
      entryFee: "₹50 (Indian), ₹200 (Foreign Tourist)",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9T4KLWrsKt0C3KOr1LPl0Lkcg8w-rcgXMxtDZApd2d0ZRZoGo1d_uOXg&s=10",
      category : "heritage",
      state : "Rajasthan",
      stateId : 21,
    },

    {
      title: "Jal Mahal",
      description:
        "Jal Mahal is a beautiful palace situated in the middle of Man Sagar Lake. It is one of Jaipur's most photographed landmarks.",
      city: "Jaipur",
      location: "Amer Road, Jaipur, Rajasthan",
      bestTime: "October to March",
      timings: "View from outside anytime",
      entryFee: "Free",
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_w_-cDMx_BgBqP3Rvqbak2VkUv-ZhQAEpX8naQ2oKWA&s=10",
      category : "heritage",
      state : "Rajasthan",
      stateId : 21,
    },

    {
      title: "City Palace",
      description:
        "The City Palace is a royal residence and museum complex showcasing Rajput architecture, courtyards, and heritage artifacts.",
      city: "Jaipur",
      location: "Jaipur, Rajasthan",
      bestTime: "October to March",
      timings: "9:30 AM - 5:00 PM",
      entryFee: "₹300 onwards",
      image:"https://upload.wikimedia.org/wikipedia/commons/a/a4/Chandra_Mahal%2C_City_Palace%2C_Jaipur%2C_20191218_0951_9043.jpg",
      category : "heritage",
      state : "Rajasthan",
      stateId : 21,
    },

    {
      title: "Jaisalmer Fort",
      description:
        "One of the few living forts in the world, Jaisalmer Fort houses shops, temples, and residences within its walls.",
      city: "Jaisalmer",
      location: "Jaisalmer, Rajasthan",
      bestTime: "November to February",
      timings: "Open all day",
      entryFee: "Free",
      image:"https://i0.wp.com/www.rajasthandirect.com/wp-content/uploads/2012/11/Jaisalmer-Fort.jpg?fit=550%2C412&ssl=1",
      category:"heritage",
      state : "Rajasthan",
      stateId : 21,
    },
    {
      title: "Lake Pichola",
      description:
        "A picturesque artificial lake surrounded by palaces, temples, and hills. It is one of Udaipur's major attractions.",
      city: "Udaipur",
      location: "Udaipur, Rajasthan",
      bestTime: "September to March",
      timings: "10:00 AM - 6:00 PM (Boat Ride)",
      entryFee: "Free (Boat rides charge separately)",
      image:"https://upload.wikimedia.org/wikipedia/commons/d/d2/Udaipur_Lake_India.JPG",
      category:"nature",
      state : "Rajasthan",
      stateId : 21,
    },
    {
    title: "Tsomgo Lake",
    description: "Glacial lake surrounded by snow-capped mountains and one of Sikkim's top attractions.",
    city: "Gangtok",
    location: "East Sikkim",
    bestTime: "March to May",
    timings: "8:00 AM - 3:00 PM",
    entryFee: "Permit Required",
    image:"https://images.unsplash.com/photo-1631643171709-626f69ca8be0?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"adventure",
    state: "Sikkim",
    stateId: 22,
},
{
    title: "Nathula Pass",
    description: "Historic mountain pass on the Indo-China border offering spectacular Himalayan views.",
    city: "Gangtok",
    location: "Nathula",
    bestTime: "May to October",
    timings: "8:00 AM - 1:00 PM",
    entryFee: "Permit Required",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSokJm71PcD8mgD0Zujg7RHEnni81TLmuSBBtdkqw4BTEQou6yyhFuGsI8&s=10",
    category:"mountain",
    state: "Sikkim",
    stateId: 22,
},
{
    title: "Yumthang Valley",
    description: "Known as the Valley of Flowers, famous for colorful blooms and scenic beauty.",
    city: "Lachung",
    location: "North Sikkim",
    bestTime: "February to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1697363572125-d54c1a30592e?q=80&w=1186&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"mountain",
    state: "Sikkim",
    stateId: 22,
},
{
    title: "Pelling",
    description: "Popular hill_station offering magnificent views of Mount Kanchenjunga.",
    city: "Pelling",
    location: "West Sikkim",
    bestTime: "March to May",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1724600457405-a7eeabcff6b5?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"nature",
    state: "Sikkim",
    stateId: 22,
},
{
    title: "Rumtek Monastery",
    description: "One of the largest and most important Buddhist monasteries in Sikkim.",
    city: "Gangtok",
    location: "Rumtek",
    bestTime: "Throughout the Year",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹10",
    image:"https://www.trawell.in/admin/images/upload/723415296Gangtok_Rumtek_Monastery_Main.jpg",
    category:"heritage",
    state: "Sikkim",
    stateId: 22,
},

{
    title: "Meenakshi Amman Temple",
    description: "Historic temple dedicated to Goddess Meenakshi and a masterpiece of Dravidian architecture.",
    city: "Madurai",
    location: "Madurai City",
    bestTime: "October to March",
    timings: "5:00 AM - 10:00 PM",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1697729444936-8c6a6f643312?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"religious",
    state: "Tamil Nadu",
    stateId: 23,
},
{
    title: "Marina Beach",
    description: "One of the world's longest urban beaches and a major attraction in Chennai.",
    city: "Chennai",
    location: "Marina Beach Road",
    bestTime: "November to February",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1675039871449-62f86fb78a70?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"beach",
    state: "Tamil Nadu",
    stateId: 23,
},
{
    title: "Ooty",
    description: "Famous hill_station known for tea gardens, lakes, and pleasant weather.",
    city: "Ooty",
    location: "Nilgiris District",
    bestTime: "October to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/m_Ooty_main_tv_destination_img_1_l_764_1269.jpg",
    category:"hill_station",
    state: "Tamil Nadu",
    stateId: 23,
},
{
    title: "Rameswaram",
    description: "Sacred pilgrimage destination and one of the Char Dham sites.",
    city: "Rameswaram",
    location: "Ramanathapuram District",
    bestTime: "October to April",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://plus.unsplash.com/premium_photo-1697729444936-8c6a6f643312?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"religious",
    state: "Tamil Nadu",
    stateId: 23,
},
{
    title: "Kodaikanal",
    description: "Scenic hill_station famous for lakes, waterfalls, and misty landscapes.",
    city: "Kodaikanal",
    location: "Dindigul District",
    bestTime: "September to May",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1692792284356-f80113facd09?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"hill_station",
    state: "Tamil Nadu",
    stateId: 23,
},

{
    title: "Charminar",
    description: "Iconic monument and symbol of Hyderabad built in 1591.",
    city: "Hyderabad",
    location: "Old City",
    bestTime: "October to March",
    timings: "9:30 AM - 5:30 PM",
    entryFee: "₹25",
    image:"https://images.unsplash.com/photo-1696941515998-d83f24967aca?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"heritage",
    state: "Telangana",
    stateId: 24,
},
{
    title: "Golconda Fort",
    description: "Historic fort known for its impressive architecture and acoustic design.",
    city: "Hyderabad",
    location: "Golconda",
    bestTime: "October to March",
    timings: "9:00 AM - 5:30 PM",
    entryFee: "₹25",
    image:"https://images.unsplash.com/photo-1470075446540-4391a96ec621?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"heritage",
    state: "Telangana",
    stateId: 24,
},
{
    title: "Ramoji Film City",
    description: "World's largest integrated film studio complex and entertainment destination.",
    city: "Hyderabad",
    location: "Abdullapurmet",
    bestTime: "October to March",
    timings: "9:00 AM - 5:30 PM",
    entryFee: "₹1350",
    image:"https://media.insider.in/image/upload/w_800/v1757165220/ohc7n2o48cwuil57oqsa.png",
    category:"adventure",
    state: "Telangana",
    stateId: 24,
},
{
    title: "Birla Mandir",
    description: "Beautiful white marble temple dedicated to Lord Venkateswara.",
    city: "Hyderabad",
    location: "Naubath Pahad",
    bestTime: "October to March",
    timings: "7:00 AM - 12:00 PM, 3:00 PM - 9:00 PM",
    entryFee: "Free",
    image:"https://images.unsplash.com/photo-1617540732046-c448921e862a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"religious",
    state: "Telangana",
    stateId: 24,
},
{
    title: "Warangal Fort",
    description: "Historic fort showcasing the grandeur of the Kakatiya dynasty.",
    city: "Warangal",
    location: "Warangal District",
    bestTime: "October to March",
    timings: "10:00 AM - 7:00 PM",
    entryFee: "₹15",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9g9L58bMKssyieOAiHZ15ZtMH7BWJWQyQffX8wjl0rAJi7lqQnEE0X57Q&s=10",
    category:"heritage",
    state: "Telangana",
    stateId: 24,
},
  {
    title: "Ujjayanta Palace",
    description: "Magnificent royal palace showcasing Tripura's rich history and culture.",
    city: "Agartala",
    location: "Central Agartala",
    bestTime: "October to March",
    timings: "10:00 AM - 5:00 PM",
    entryFee: "₹25",
    image:"https://tse3.mm.bing.net/th/id/OIP.fEfXYszAaeiiTbkrdsFEMwHaC9?pid=Api&P=0&h=180",
    category:"heritage",
    state: "Tripura",
    stateId: 25,
},
{
    title: "Neermahal",
    description: "Beautiful water palace built in the middle of Rudrasagar Lake.",
    city: "Melaghar",
    location: "Rudrasagar Lake",
    bestTime: "October to February",
    timings: "9:00 AM - 5:00 PM",
    entryFee: "₹80",
    image:"https://upload.wikimedia.org/wikipedia/commons/3/38/Neer_Mahal%2C_the_water_palace_of_Tripura_02.jpg",
    category:"heritage",
    state: "Tripura",
    stateId: 25,
},
{
    title: "Tripura Sundari Temple",
    description: "One of the 51 Shakti Peethas and an important Hindu pilgrimage site.",
    city: "Udaipur",
    location: "Gomati District",
    bestTime: "October to March",
    timings: "5:00 AM - 10:00 PM",
    entryFee: "Free",
    image:"https://www.templefolks.com/templefolks_admin/public/uploads/products/Tripura-Sundari-Temple-1784264.jpg",
    category:"religious",
    state: "Tripura",
    stateId: 25,
},
{
    title: "Unakoti",
    description: "Ancient rock carvings and stone sculptures dating back centuries.",
    city: "Kailashahar",
    location: "Unakoti District",
    bestTime: "October to March",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹20",
    image:"https://images.unsplash.com/photo-1695150854909-a00039a284b8?q=80&w=929&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"heritage",
    state: "Tripura",
    stateId: 25,
},
{
    title: "Sepahijala wildlife Sanctuary",
    description: "Popular wildlife sanctuary known for diverse flora, fauna, and birdlife.",
    city: "Bishalgarh",
    location: "Sepahijala District",
    bestTime: "November to February",
    timings: "8:00 AM - 4:00 PM",
    entryFee: "₹10",
    image:"https://static.tripclap.com/uploads/places/850X450/sepahijala-wildlife-sanctuary_1632299822-5676e.jpg",
    category:"wildlife",
    state: "Tripura",
    stateId: 25,
},

{
    title: "Taj Mahal",
    description: "UNESCO World Heritage Site and one of the Seven Wonders of the World.",
    city: "Agra",
    location: "Dharmapuri, Agra",
    bestTime: "October to March",
    timings: "6:00 AM - 6:30 PM",
    entryFee: "₹50",
    image:"https://plus.unsplash.com/premium_photo-1661885523029-fc960a2bb4f3?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"heritage",
    state: "Uttar Pradesh",
    stateId: 26,
},
{
    title: "Kashi Vishwanath Temple",
    description: "One of the most sacred Hindu temples dedicated to Lord Shiva.",
    city: "Varanasi",
    location: "Lahori Tola",
    bestTime: "October to March",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://tse1.mm.bing.net/th/id/OIP.7DDh4HDTH6W5Mz7M1yDqMwHaEK?pid=Api&P=0&h=180",
    category:"religious",
    state: "Uttar Pradesh",
    stateId: 26,
},
{
    title: "Ayodhya Ram Mandir",
    description: "Grand temple dedicated to Lord Shri Ram at his birthplace.",
    city: "Ayodhya",
    location: "Ram Janmabhoomi",
    bestTime: "October to March",
    timings: "6:00 AM - 10:00 PM",
    entryFee: "Free",
    image:"https://thejuniorage.com/wp-content/uploads/2024/01/1-Ayodhya-ram-mandir.png",
    category:"religious",
    state: "Uttar Pradesh",
    stateId: 26,
},
{
    title: "Fatehpur Sikri",
    description: "Historic Mughal city and UNESCO World Heritage Site.",
    city: "Agra",
    location: "Fatehpur Sikri",
    bestTime: "October to March",
    timings: "6:00 AM - 6:00 PM",
    entryFee: "₹50",
    image:"https://i0.wp.com/somanytraveltales.com/wp-content/uploads/2021/12/Anup-Talao-2-Fatehpur-1-scaled.jpg?fit=1024%2C697&ssl=1",
    category:"religious",
    state: "Uttar Pradesh",
    stateId: 26,
},
{
    title: "Bara Imambara",
    description: "Architectural marvel famous for its Bhool Bhulaiya labyrinth.",
    city: "Lucknow",
    location: "Husainabad",
    bestTime: "October to March",
    timings: "6:00 AM - 5:00 PM",
    entryFee: "₹50",
    image:"https://www.trawell.in/admin/images/upload/006238776Lucknow_Bara_Imambara_Main.jpg",
    category:"heritage",
    state: "Uttar Pradesh",
    stateId: 26,
},

{
    title: "Kedarnath Temple",
    description: "One of the twelve Jyotirlingas and an important pilgrimage destination.",
    city: "Kedarnath",
    location: "Rudraprayag District",
    bestTime: "May to October",
    timings: "4:00 AM - 9:00 PM",
    entryFee: "Free",
    image:"https://vl-prod-static.b-cdn.net/system/images/000/885/875/d1bafc6e8a413da7110fcd039290b579/original/ChatGPT_Image_Feb_4__2026__12_39_56_PM.png",
    category:"religious",
    state: "Uttarakhand",
    stateId: 27,
},
{
    title: "Badrinath Temple",
    description: "Sacred Char Dham pilgrimage site dedicated to Lord Vishnu.",
    city: "Badrinath",
    location: "Chamoli District",
    bestTime: "May to October",
    timings: "4:30 AM - 9:00 PM",
    entryFee: "Free",
    image:"https://s7ap1.scene7.com/is/image/incredibleindia/badrinath-temple-badrinath-uttarakhand-city-ff?qlt=82&ts=1726646641575",
    category:"religious",
    state: "Uttarakhand",
    stateId: 27,
},
{
    title: "Nainital Lake",
    description: "Beautiful natural lake surrounded by hills and vibrant markets.",
    city: "Nainital",
    location: "Nainital Town",
    bestTime: "March to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtWJ89t7A7hJymtWCROf_RLzvxcvexeygmXPbBiJ-OPw&s=10",
    category:"nature",
    state: "Uttarakhand",
    stateId: 27,
},
{
    title: "Valley of Flowers",
    description: "UNESCO World Heritage Site famous for alpine flowers and biodiversity.",
    city: "Chamoli",
    location: "Valley of Flowers National Park",
    bestTime: "July to September",
    timings: "7:00 AM - 5:00 PM",
    entryFee: "₹150",
    image:"https://plus.unsplash.com/premium_photo-1711697144877-b068f748bcd1?q=80&w=715&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category:"nature",
    state: "Uttarakhand",
    stateId: 27,
},
{
    title: "Mussoorie",
    description: "Popular hill_station known as the Queen of the Hills.",
    city: "Mussoorie",
    location: "Dehradun District",
    bestTime: "March to June",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://cdnbbsr.s3waas.gov.in/s3ad9db03f1a981f9593f55f9c6ac84644/uploads/2025/03/20250328836639373.jpg",
    category:"hill_station",
    state: "Uttarakhand",
    stateId: 27,
},

{
    title: "Victoria Memorial",
    description: "Iconic marble monument and museum reflecting Kolkata's colonial heritage.",
    city: "Kolkata",
    location: "Maidan",
    bestTime: "October to March",
    timings: "10:00 AM - 5:00 PM",
    entryFee: "₹30",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKgohCjr0clGwZA4cQ-v2SXVJe0nihOYeAdegQzfxn_rqiACCsHvyj4TuR&s=10",
    category:"heritage",
    state: "West Bengal",
    stateId: 28,
},
{
    title: "Darjeeling Himalayan Railway",
    description: "UNESCO-listed toy train journey through scenic Himalayan landscapes.",
    city: "Darjeeling",
    location: "Darjeeling Town",
    bestTime: "March to May",
    timings: "Train Schedule Based",
    entryFee: "Ticket Charges Apply",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIGfI9L9FWBerwgxH_6StNaqZlITdUjpMfHHQsRNY8mIVYQEUW2iKkkJo&s=10",
    category:"nature",
    state: "West Bengal",
    stateId: 28,
},
{
    title: "Sundarbans National Park",
    description: "World's largest mangrove forest and home to the Royal Bengal Tiger.",
    city: "South 24 Parganas",
    location: "Sundarbans",
    bestTime: "November to February",
    timings: "8:00 AM - 5:00 PM",
    entryFee: "₹60",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4RJbMOtmzr5TCoLBVjUx3WkIStQKbZFRty8Q0P702v9fO9GrurSs-XUw&s=10",
    category:"wildlife",
    state: "West Bengal",
    stateId: 28,
},
{
    title: "Kalimpong",
    description: "Picturesque hill town known for monasteries, orchids, and mountain views.",
    city: "Kalimpong",
    location: "Kalimpong District",
    bestTime: "March to May",
    timings: "Open 24 Hours",
    entryFee: "Free",
    image:"https://s7ap1.scene7.com/is/image/incredibleindia/lord-buddha-statue-1-kalimpong-wb-attr-nearby?qlt=82&ts=1726645005259",
    category:"religios",
    state: "West Bengal",
    stateId: 28,
},
{
    title: "Dakshineswar Kali Temple",
    description: "Famous riverside temple dedicated to Goddess Kali.",
    city: "Kolkata",
    location: "Dakshineswar",
    bestTime: "October to March",
    timings: "6:00 AM - 12:30 PM, 3:00 PM - 8:30 PM",
    entryFee: "Free",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoDytj_OEUMCe53I3fL4V1gb3kRkQFwj4eWIQLd-i8Iw&s",
    category:"religious",
    state: "West Bengal",
    stateId: 28,
},



];

module.exports = placeData;